2.0.1

diff --git a/bashible b/bashible
--- a/bashible
+++ b/bashible
@@ -221,21 +221,6 @@ may_fail() {
   return 0
 }
 
-# deprecated; use "not empty" instead
-nonempty() {
-  quiet type $1 || fail "nonempty: command '$1' not found"
-  local buf
-  eval "
-    buf=\"\`  \"\$@\"  \`\" 
-  "
-  local ex=$?
-  echo "$buf"
-  if test $ex -gt 0 ; then
-     fail "nonempty: command '$@' exited $ex";
-  fi
-  test ${#buf} -gt 0  # is returned
-}
-
 not() {
   quiet type $1 || fail "not: command '$1' not found"
   "$@" && return 1 || return 0
@@ -315,7 +300,7 @@ cat <<END_OF_BLEMPLATE
 $(< "${path}" )
 END_OF_BLEMPLATE" </dev/stdin 2>&1 1>&3
 `
-    test "${#stderr}" -eq 0 || { echo $stderr; print_error "template '$path' failed"; return 1; }
+    test "${#stderr}" -eq 0 || { echo $stderr>/dev/stderr; print_error "template '$path' failed"; return 1; }
   ) > $res
 }
 
@@ -368,7 +353,7 @@ comment_line_matching() {
   local path=$2
   test ${#match} -eq 0 && { print_error "comment_line_matching: empty regexp is not allowed!"; return 1; }
   test ! -f "$path" && { print_error "comment_line_matching: file '$path' not found"; return 1; }
-  sed -i -r -e 's/^([^#]*'$match'.*)$/#\1/' "$path"
+  sed -i -r -e 's/^([^#]*'"$match"'.*)$/#\1/' "$path"
 }
 
 copy() {
@@ -455,7 +440,7 @@ uncomment_line_matching() {
   local path=$2
   test ${#match} -eq 0 && { print_error "uncomment_line_matching: empty regexp is not allowed!"; return 1; }
   test ! -f "$path" && { print_error "uncomment_line_matching: file '$path' not found"; return 1; }
-  sed -i -r -e 's/^ *#(.*?'$match'.*)$/\1/' "$path"
+  sed -i -r -e 's/^ *#(.*?'"$match"'.*)$/\1/' "$path"
 }
 
 wait_for_tcp() {
