several functions fixes, documentation for them

diff --git a/bashible b/bashible
--- a/bashible
+++ b/bashible
@@ -45,29 +45,13 @@ if [ -z "${_BLEBOOK}" ]; then
 fi
 
 
-### CORE FUNCTIONS ####
+### INTERNAL FUNCTIONS ####
 
+# searches an array for an element; used internally
 containsElement() {
   local e
   for e in "${@:2}"; do [[ "$e" == "$1" ]] && return 0; done
   return 1
-}
-
-quiet() {
-   "$@" >/dev/null 2>&1
-}
-
-fail() {
-   echo -e "\033[1;37;41m ${_NAV}: $*, exiting \033[0m"
-   exit 1
-}
-
-info() {
-  echo -e "   \033[32m($*)\033[0m"
-}
-
-warn() {
-  echo -e "   \033[31m($*)\033[0m"
 }
 
 print_start() {
@@ -84,6 +68,58 @@ print_finish() {
 
 print_task() {
     echo -e "\033[37m - $* \033[0m"
+}
+
+
+### CORE FUNCTIONS ####
+
+# represents a block; always chdirs to the base_dir (default = current directory)
+@() {
+   _BLOCKS_STARTED=1
+   _SKIP=0
+   cd "${_BASE_DIR}" || fail "can't chdir to base dir '${_BASE_DIR}'"
+   print_block $*
+}
+
+# represents a task; if the task fails, the bashible script is stopped
+# if the block has been skipped, does nothing
+-() {
+   if [ "${_SKIP}" != 1 ]; then
+     print_task $*
+     "$@" || fail "'$@' failed (in `pwd`)";
+   fi
+}
+
+already() {
+  if [ "${_BLOCKS_STARTED}" = 0 ]; then
+     warn "already, stopping here"
+     print_finish
+     exit
+  else
+     info "already, skipping following tasks"
+     _SKIP=1
+  fi
+}
+
+# the same as skip_if, just a different message
+already_if() {
+  "$@" && already || return 0
+}
+
+# run following command as an user
+as() {
+   local user=$1; shift
+   # can't be -i (login shell) otherwise -E won't work, it would also chdir to homedir
+   # PATH is usually erased by sudo, has to be preserved explicitly
+   /usr/bin/env sudo -E -u "$user" /usr/bin/env env -- PATH="${PATH}" _IMPORTED="${_IMPORTED}" "${_BASHIBLE}" -- "$@" || fail "sudo command failed (in `pwd`)"
+}
+
+# set base dir (will be chdired to it on each @ block)
+base_dir() {
+  _BASE_DIR=`readlink -e "$1"` # get absolute path
+  if [ -z "${_BASE_DIR}" ]; then
+    fail "base_dir: readlink -e '$1' failed"
+  fi
 }
 
 # use to call a bashible "playbook" instead of sourcing it
@@ -112,43 +148,9 @@ call() {
   ) || exit 1
 }
 
-# set base dir (will be chdired to it on each @ block)
-base_dir() {
-  _BASE_DIR=`readlink -e "$1"` # get absolute path
-  if [ -z "${_BASE_DIR}" ]; then
-    fail "base_dir: readlink -e '$1' failed"
-  fi
-  mkdir -p "${_BASE_DIR}" || fail "can't create base dir"
-}
-
-
-reset_base_dir() {
-  _BASE_DIR="${_ORIG_BASE_DIR}"
-}
-
-# represents a block; always chdirs to the base_dir (default = current directory)
-@() {
-   _BLOCKS_STARTED=1
-   _SKIP=0
-   cd "${_BASE_DIR}" || fail "can't chdir to base dir '${_BASE_DIR}'"
-   print_block $*
-}
-
-# represents a task; if the task fails, the bashible script is stopped
-# if the block has been skipped, does nothing
--() {
-   if [ "${_SKIP}" != 1 ]; then
-     print_task $*
-     "$@" || fail "'$@' failed (in `pwd`)";
-   fi
-}
-
-# run following command as an user
-as() {
-   local user=$1; shift
-   # can't be -i (login shell) otherwise -E won't work, it would also chdir to homedir
-   # PATH is usually erased by sudo, has to be preserved explicitly
-   /usr/bin/env sudo -E -u "$user" /usr/bin/env env -- PATH="${PATH}" _IMPORTED="${_IMPORTED}" "${_BASHIBLE}" -- "$@" || fail "sudo command failed (in `pwd`)"
+fail() {
+   echo -e "\033[1;37;41m ${_NAV}: $*, exiting \033[0m"
+   exit 1
 }
 
 import() {
@@ -156,6 +158,32 @@ import() {
       _IMPORTED="${_IMPORTED}$1:"
       source "$1"
    fi
+}
+
+info() {
+  echo -e "   \033[32m($*)\033[0m"
+}
+
+may_fail() {
+  "$@"
+  return 0
+}
+
+# opposite to only_on
+not_on() {
+   if containsElement "${_HOSTNAME}" "$@"; then
+      if [ "${_BLOCKS_STARTED}" = 0 ]; then
+         warn "skipping all tasks here on ${_HOSTNAME}"
+         stop
+      else
+         warn "not on ${_HOSTNAME}, skipping"
+         _SKIP=1
+      fi
+   fi
+}
+
+not() {
+  "$@" && return 1 || return 0
 }
 
 # skip next tasks if the current hostname is not in defined
@@ -172,6 +200,38 @@ only_on() {
    fi
 }
 
+quiet() {
+   "$@" >/dev/null 2>&1
+}
+
+reset_base_dir() {
+  _BASE_DIR="${_ORIG_BASE_DIR}"
+}
+
+skip() {
+   if [ "${_BLOCKS_STARTED}" = 0 ]; then
+     info "skipping all tasks of the blebook"
+     exit
+   else
+      info "skipping following tasks"
+     _SKIP=1
+   fi
+}
+
+skip_if() {
+  "$@" && skip || return 0
+}
+
+stop() {
+  info "stopping execution of the script"
+  print_finish
+  exit
+}
+
+stop_if() {
+  "$@" && stop || return 0
+}
+
 # skip next tasks if the tag is not in required tags
 tag() {
    if [ "${#_TAGS[@]}" -gt 0 ]; then
@@ -182,9 +242,8 @@ tag() {
    fi
 }
 
-may_fail() {
-  "$@"
-  return 0
+warn() {
+  echo -e "   \033[31m($*)\033[0m"
 }
 
 when() {
@@ -201,59 +260,8 @@ unless() {
    fi
 }
 
-not() {
-  "$@" && return 1 || return 0
-}
-
-stop() {
-  info "stopping execution of the script"
-  print_finish
-  exit
-}
-
-stop_if() {
-  "$@" && stop || return 0
-}
-
-already() {
-   info "already, skipping following tasks"
-   _SKIP=1
-}
-
-# the same as skip_if, just a different message
-already_if() {
-  "$@" && already || return 0
-}
-
-skip() {
-   info "skipping following tasks"
-   _SKIP=1
-}
-
-skip_if() {
-  "$@" && skip || return 0
-}
-
 
 ### USEFUL HELPERS ###
-
-is_empty() {
-   [ -z "`eval echo "$""$1"`" ]
-}
-
-symlink() {
-  src=$1
-  dest=$2
-  if test -L "$2"; then
-    local curr="`readlink "$2"`"
-    if [ "$curr" != "$1" ]; then
-       fail "symlink exists already, but points to different location: $curr (should $2)"
-    fi
-    info "already"
-  else
-    ln -s "$1" "$2" || fail "can't create symlink"
-  fi
-}
 
 add_line() {
    local line="$1"
@@ -277,66 +285,11 @@ append_line() {
    fi
 }
 
-prepend_line() {
-   local line="$1"
-   local path="$2"
-   quiet head -n 1 "$path" || fail "can't read file '$path'"
-   if [ "` head -n 1 "$path" `" != "$line" ]; then
-     sed -i "1i $line" "$path" || fail "can't edit file '$path'"
-   else
-     info "already"
-   fi
-}
-
-comment_line_with() {
+comment_line_matching() {
    local match="$1"
    local path="$2"
    [ ! -f "$path" ] && fail "file '$path' not found"
    sed -i -r -e 's/^([^#]*'$match'.*)$/#\1/' "$path"
-}
-
-uncomment_line_with() {
-   local match="$1"
-   local path="$2"
-   [ ! -f "$path" ] && fail "file '$path' not found"
-   sed -i -r -e 's/^ *#(.*?'$match'.*)$/\1/' "$path"
-}
-
-replace_line_with() {
-   local match="$1"
-   local replacement="$2"
-   local path="$3"
-   [ ! -f "$path" ] && fail "file '$path' not found"
-   sed -i "s\\$match\\$replace\\" "$replacement" "$path"
-}
-
-is_rpm_installed() {
-   for i in `rpm -q "$1"`; do
-      version="${i##$1}"
-      if echo "$version" | egrep -q -e "^-[0-9]"; then
-        return 0
-      fi
-   done
-   return 1
-}
-
-timeout() {
-   time=$1; shift
-   if ! /usr/bin/env timeout "$time" "${_BASHIBLE}" -- "$@"; then
-      fail "timeout expired"
-   fi
-}
-
-yum_install() {
-   while [ -n "$1" ]; do
-     if ! is_rpm_installed "$1"; then
-        info "$1 seems to be not installed yet"
-        yum install -y "$1" || fail "can't install $1"
-     else
-        info "$1 already"
-     fi
-     shift
-   done
 }
 
 # WARN: gem_install is provided by RVM and it takes precedence! therefore this is install_gem
@@ -351,11 +304,79 @@ install_gem() {
    done
 }
 
+is_rpm_installed() {
+   for i in `rpm -q "$1"`; do
+      version="${i##$1}"
+      if echo "$version" | egrep -q -e "^-[0-9]"; then
+        return 0
+      fi
+   done
+   return 1
+}
+
+prepend_line() {
+   local line="$1"
+   local path="$2"
+   quiet head -n 1 "$path" || fail "can't read file '$path'"
+   if [ "` head -n 1 "$path" `" != "$line" ]; then
+     sed -i "1i $line" "$path" || fail "can't edit file '$path'"
+   else
+     info "already"
+   fi
+}
+
+remove_line_matching() {
+   local match="$1"
+   local path="$2"
+   [ ! -f "$path" ] && fail "file '$path' not found"
+   sed -i "\\$line\\d" "$path" || fail "can't edit file '$path'"
+}
+
+replace_matching() {
+   local match="$1"
+   local replacement="$2"
+   local path="$3"
+   [ ! -f "$path" ] && fail "file '$path' not found"
+   sed -i "s\\$match\\$replace\\" "$replacement" "$path"
+}
+
+symlink() {
+  local src=$1
+  local dest=$2
+  if test -L "$2"; then
+    local curr="`readlink "$2"`"
+    if [ "$curr" != "$1" ]; then
+       fail "symlink exists already, but points to different location: $curr (should $2)"
+    fi
+    info "already"
+  else
+    ln -s "$1" "$2" || fail "can't create symlink"
+  fi
+}
+
+timeout() {
+   local time=$1; shift
+   if ! /usr/bin/env timeout "$time" "${_BASHIBLE}" -- "$@"; then
+      fail "timeout expired"
+   fi
+}
+
+uncomment_line_matching() {
+   local match="$1"
+   local path="$2"
+   [ ! -f "$path" ] && fail "file '$path' not found"
+   sed -i -r -e 's/^ *#(.*?'$match'.*)$/\1/' "$path"
+}
+
+var_is_empty() {
+   [ -z "`eval echo "$""$1"`" ]
+}
+
 # wait_for_tcp 10.0.3.188:80 up
 # wait_for_tcp 10.0.3.188:80 down
 wait_for_tcp() {
-  what="$1"
-  up="$2"
+  local what="$1"
+  local up="$2"
   if [ "$up" = up ]; then
      while ! netstat -lnt | grep "$what" | grep -q 'LISTEN'; do sleep 1; done
   elif [ "$up" = down ]; then
@@ -365,6 +386,19 @@ wait_for_tcp() {
   fi
   return 0
 }
+
+yum_install() {
+   while [ -n "$1" ]; do
+     if ! is_rpm_installed "$1"; then
+        info "$1 seems to be not installed yet"
+        yum install -y "$1" || fail "can't install $1"
+     else
+        info "$1 already"
+     fi
+     shift
+   done
+}
+
 
 ### DO THE PROCESS ###
 
