i_a_child removed, toplevel added; use 'not toplevel' instead 'i_am_child'

diff --git a/bashible b/bashible
--- a/bashible
+++ b/bashible
@@ -95,6 +95,9 @@ call() {
   fi
 }
 
+delayed_call() {
+  absolutePath "$1" >> "${_BLE_DELAYED}" || fail "can't write to _BLE_DELAYED file (${_BLE_DELAYED})"
+}
 
 empty() {
   quiet type $1 || fail "empty: command '$1' not found"
@@ -170,10 +173,6 @@ import() {
   fi
 }
 
-i_am_child() {
-  test "${_BLE_LEVEL}" -ge 1
-}
-
 may_fail() {
   quiet type $1 || fail "may_fail: command '$1' not found"
   "$@"
@@ -183,10 +182,6 @@ may_fail() {
 not() {
   quiet type $1 || fail "not: command '$1' not found"
   "$@" && return 1 || return 0
-}
-
-delayed_call() {
-  absolutePath "$1" >> "${_BLE_DELAYED}" || fail "can't write to _BLE_DELAYED file (${_BLE_DELAYED})"
 }
 
 print_error() {
@@ -247,6 +242,10 @@ END_OF_BLEMPLATE" </dev/stdin 2>&1 1>&3
 `
     test "${#stderr}" -eq 0 || { echo $stderr>/dev/stderr; print_error "template '$path' failed"; return 1; }
   ) > $res
+}
+
+toplevel() {
+  test "${_BLE_LEVEL}" -eq 1
 }
 
 var_empty() {
